### ISSUE TITLE
Feature request: `--detail-level regressions`

### ISSUE THREAD

**Issue by thislooksfun** [beuss-git/wpt-results-analyzer#2]
When using this tool I am mostly looking for details about regressed tests. Newly passing tests are great, but they are done. I still need to action on the ones that are failing. However currently I can only list all details or no details. This is an issue if, for example, you make a change that adds 100 new successful (sub)tests, but also adds 50 new crashes/fails. I want to list the new fails so I can investigate them, but if I add `--detail-level all` or `--detail-level changed` combined with `--max-details 50` to list all the failures it clutters up the output with all the newly passing (sub)tests.

I would love to have a setting to make it only print the detailed failures/regressions, and not print the passes.

**Comment by beuss-git** [comment]
This is a good suggestion and I considered adding something similar during initial development, I was just afraid of bloating the CLI arguments, but I think it is worth it in this case.

I've implemented this functionality with a new `--failures-only` flag that you can use to filter out passing tests from the detailed output. Instead of adding a new detail level, this flag works in combination with existing detail levels which I think makes more sense.
